import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
  /*   <> */
  <div className = "contentt">
   
      <Head>
        <title>MonoSolution web page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <Link href="/form"> 
      <a className={styles.btn}> See Liver Center</a>
      </Link>
      
  </div>  
  
  )
}
